# .github/workflows/build-windows.yml

name: Build for Windows

# 控制工作流的触发条件
on:
  # 允许你从 Actions 标签页手动触发此工作流
  workflow_dispatch:

jobs:
  build-windows:
    # 明确指定运行器为 Windows Server 2022，避免未来系统更新带来的问题
    runs-on: windows-2022

    steps:
      # 第一步：检出你的代码
      - name: Checkout repository
        uses: actions/checkout@v4 # 升级到 v4 版本
        with:
          submodules: 'recursive'

      # 第二步：安装 Rust 工具链
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 第三步：安装 LLVM
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '15'

      # 第四步：缓存依赖项
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      # 第五步：编译项目
      - name: Build Phira
        run: cargo build --release --package phira
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
          VCPKGRS_DYNAMIC: "1"

      # 第六步：准备打包文件
      - name: Package assets
        run: |
          mkdir release
          cp target/release/phira.exe release/
          cp -r assets release/

      # 第七步：上传构建产物 (已升级到 v4)
      # 使用最新版本的 actions/upload-artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: phira-windows-build
          path: release/
