name: Build Rust Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      artifacts: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          profile: minimal
          url: https://mirrors.aliyun.com/rustup   # 使用阿里云镜像

      - name: Build project
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3.4.0
        with:
          name: release-binaries
          path: target/release/
