# .github/workflows/build-windows.yml

name: Build for Windows with vcpkg

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 第二步：安装 Rust 工具链
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 第三步 [全新]：使用 vcpkg 安装 MSVC 兼容的 FFmpeg
      - name: Install FFmpeg using vcpkg
        uses: an-tao/vcpkg-action@v3
        with:
          # 我们需要 FFmpeg 的 x64-windows-static 版本
          # 'static' 意味着所有库都会被直接编译进最终的 .exe 文件，无需附带 .dll
          vcpkg_static: true
          packages: ffmpeg

      # 第四步：缓存依赖项
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      # 第五步：编译项目
      # vcpkg-action 会自动设置所有必要的环境变量 (包括 LIB, PATH 等)
      - name: Build Phira
        run: cargo build --release
        shell: bash

      # 第六步：准备打包文件
      - name: Package assets
        run: |
          mkdir release
          cp target/release/phira.exe release/
          cp -r assets release/

      # 第七步：上传构建产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: phira-windows-build
          path: release/
