# .github/workflows/build-windows.yml

name: Build for Windows with Diagnostics

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      # 第一步至第四步保持不变
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '15'
      - name: Install FFmpeg
        run: choco install ffmpeg -y

      # ======================= 调试步骤开始 (已修正) =======================

      # 调试步骤 1: 使用固定路径显示 FFmpeg 的文件结构
      - name: '[DEBUG] Show FFmpeg Path and Directory Structure'
        run: |
          FFMPEG_INSTALL_DIR="C:/ProgramData/chocolatey/lib/ffmpeg/tools"
          echo "--- Using Hardcoded FFmpeg Install Path ---"
          echo "$FFMPEG_INSTALL_DIR"
          echo "--- FFmpeg Directory Listing ---"
          ls -R "$FFMPEG_INSTALL_DIR"
        shell: bash

      # 调试步骤 2: 确认 Rust 工具链信息 (无变化)
      - name: '[DEBUG] Show Rust Toolchain Info'
        run: rustc -vV
        shell: bash

      # 第五步：使用固定路径为编译器和运行时配置 FFmpeg 路径 (已修正)
      - name: Configure FFmpeg environment
        run: |
          FFMPEG_PATH="C:/ProgramData/chocolatey/lib/ffmpeg/tools"
          echo "Using hardcoded FFMPEG_PATH: $FFMPEG_PATH"
          echo "FFMPEG_PATH=$FFMPEG_PATH" >> $GITHUB_ENV
          echo "$FFMPEG_PATH/bin" >> $GITHUB_PATH
          echo "LIB=$FFMPEG_PATH/lib" >> $GITHUB_ENV
        shell: bash

      # 调试步骤 3: 检查编译前的所有环境变量 (无变化)
      - name: '[DEBUG] Show Environment Variables before Build'
        run: env | sort
        shell: bash

      # ======================= 调试步骤结束 =======================

      # 第六步：缓存依赖项
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      # 第七步：编译项目 (使用超详细模式)
      - name: Build Phira (Very Verbose)
        run: cargo build -vv --release
        shell: bash

      # 第八步和第九步保持不变
      - name: Package assets
        run: |
          mkdir release
          cp target/release/phira.exe release/
          cp -r assets release/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: phira-windows-build
          path: release/
