# .github/workflows/build-windows.yml

name: Build for Windows (Official Guide Method)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 第二步：安装 Rust MinGW 工具链
      - name: Install Rust toolchain (MinGW)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-pc-windows-gnu

      # 第三步 [拼写已修正]：初始化 MSYS2 环境并安装 Perl
      - name: Setup MSYS2 and install Perl
        uses: msys2/setup-msys2@v2 # <- 修正了这里的拼写错误
        with:
          update: true
          install: perl

      # 第四步：下载并解压官方文档指定的正确静态库
      - name: Download and extract OFFICIAL static libraries
        run: |
          curl -L -o prpr-avc.zip "https://teamflos.github.io/phira-docs/phira_build_guide/prpr-avc.zip"
          unzip -o prpr-avc.zip
        shell: bash

      # 第五步：缓存 Rust 依赖项
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      # 第六步：编译项目 (使用官方命令)
      - name: Build Phira
        run: cargo build --release --bin phira-main
        shell: bash

      # 第-七步：准备打包文件
      - name: Package assets
        run: |
          # 确保目标目录存在
          mkdir -p target/release/assets
          # 将 assets 文件夹的内容复制到 target/release/assets
          cp -r assets/* target/release/assets/
          # 将编译好的主程序也复制过来
          cp target/release/phira-main.exe target/release/
        shell: bash

      # 第八步：上传构建产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: phira-windows-build
          # 我们上传整个 release 文件夹，里面包含了 exe 和 assets
          path: target/release/
