name: Build for Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '15'

      # 改用vcpkg安装FFmpeg（包含静态库）
      - name: Set up vcpkg
        uses: microsoft/vcpkg-action@v5
        with:
          vcpkgVersion: '2023.12.12'
          packages: ffmpeg[core,static]  # 明确安装静态库版本
          triplet: x64-windows-static   # Windows静态链接三元组
          gitCommitId: 'your-vcpkg-commit'  # 可选：指定vcpkg的具体commit

      # 配置FFmpeg库路径（vcpkg会自动设置相关环境变量）
      - name: Configure FFmpeg paths
        run: |
          echo "LIBRARY_PATH=$env:VCPKG_INSTALLED_DIR\x64-windows-static\lib" >> $env:GITHUB_ENV
          echo "INCLUDE=$env:VCPKG_INSTALLED_DIR\x64-windows-static\include" >> $env:GITHUB_ENV
          echo "LIB=$env:VCPKG_INSTALLED_DIR\x64-windows-static\lib" >> $env:GITHUB_ENV  # Windows原生库路径变量

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build Phira
        run: cargo build --release
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
          VCPKGRS_DYNAMIC: "0"  # 使用静态链接（关键修改）

      - name: Package assets
        run: |
          mkdir release
          cp target/release/phira.exe release/
          cp -r assets release/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: phira-windows-build
          path: release/
